const MAX_EMBED_TITLE_LENGTH: Readonly<number> = 256
const MAX_EMBED_DESCRIPTION_LENGTH: Readonly<number> = 4096
const MAX_EMBED_FIELDS: Readonly<number> = 25
const MAX_EMBED_FOOTER_TEXT_LENGTH: Readonly<number> = 2048

export { MAX_EMBED_TITLE_LENGTH, MAX_EMBED_DESCRIPTION_LENGTH, MAX_EMBED_FIELDS, MAX_EMBED_FOOTER_TEXT_LENGTH }
